In [13]:
import pandas as pd

df = pd.read_csv('../data/website_data.csv')
df.head

<bound method NDFrame.head of        website  load_time  seo_score  traffic  bounce_rate
0    site1.com        2.1         88    15000           42
1    site2.com        3.8         72     9800           58
2    site3.com        4.5         60     8700           70
3    site4.com        1.9         92    21000           35
4    site5.com        2.7         80    13200           48
5    site6.com        5.2         55     7600           75
6    site7.com        3.1         78    11000           52
7    site8.com        2.3         85    14000           44
8    site9.com        4.8         62     9200           68
9   site10.com        1.7         95    25000           30
10  site11.com        3.5         74    10500           55
11  site12.com        2.9         82    12500           47
12  site13.com        4.1         66     8900           65
13  site14.com        2.0         90    18000           38
14  site15.com        3.3         76     9900           53
15  site16.com        5.5         50     7000           78
16  site17.com        2.6         83    13500           46
17  site18.com        3.9         70     9500           60
18  site19.com        1.8         93    22000           33
19  site20.com        4.3         64     8800           67
20  site21.com        2.4         86    14500           43
21  site22.com        3.7         73    10200           57
22  site23.com        5.0         58     7900           72
23  site24.com        2.2         89    16000           41
24  site25.com        3.0         79    11500           50>

In [14]:
df.describe()

       load_time  seo_score       traffic  bounce_rate
count  25.000000  25.000000     25.000000    25.000000
mean    3.292000  76.000000  12608.000000    53.080000
std     1.146342  12.767145   4734.353177    13.634882
min     1.700000  50.000000   7000.000000    30.000000
25%     2.300000  66.000000   9200.000000    43.000000
50%     3.100000  78.000000  11000.000000    52.000000
75%     4.100000  86.000000  14500.000000    65.000000
max     5.500000  95.000000  25000.000000    78.000000

In [15]:
df.sort_values(by='load_time', ascending=False)

       website  load_time  seo_score  traffic  bounce_rate
15  site16.com        5.5         50     7000           78
5    site6.com        5.2         55     7600           75
22  site23.com        5.0         58     7900           72
8    site9.com        4.8         62     9200           68
2    site3.com        4.5         60     8700           70
19  site20.com        4.3         64     8800           67
12  site13.com        4.1         66     8900           65
17  site18.com        3.9         70     9500           60
1    site2.com        3.8         72     9800           58
21  site22.com        3.7         73    10200           57
10  site11.com        3.5         74    10500           55
14  site15.com        3.3         76     9900           53
6    site7.com        3.1         78    11000           52
24  site25.com        3.0         79    11500           50
11  site12.com        2.9         82    12500           47
4    site5.com        2.7         80    13200           48
16  site17.com        2.6         83    13500           46
20  site21.com        2.4         86    14500           43
7    site8.com        2.3         85    14000           44
23  site24.com        2.2         89    16000           41
0    site1.com        2.1         88    15000           42
13  site14.com        2.0         90    18000           38
3    site4.com        1.9         92    21000           35
18  site19.com        1.8         93    22000           33
9   site10.com        1.7         95    25000           30

In [16]:
df.corr(numeric_only=True)

             load_time  seo_score   traffic  bounce_rate
load_time     1.000000  -0.994442 -0.873215     0.990644
seo_score    -0.994442   1.000000  0.882770    -0.996198
traffic      -0.873215   0.882770  1.000000    -0.911222
bounce_rate   0.990644  -0.996198 -0.911222     1.000000